name: Copy to products.groupdocs.com

on:
  push:
    branches: [ master ]
    paths:
      - 'content/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'content/**'

  workflow_dispatch:

jobs:
  copy_content:
    runs-on: ubuntu-latest

    steps:
    - name: Copy content to products.groupdocs.com
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/
        dst_path: /
        dst_owner: groupdocs
        dst_repo_name: products.groupdocs.com
        dst_branch: main
        src_branch: master